name: CI

on:
  push:
    branches: 
      - develop
      - feature/**
  pull_request:
    branches: 
      - develop

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Horizons.sln
      Test_Project_Path: Horizons.Tests.Unit/Horizons.Tests.Unit.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: dotnet restore $env:Solution_Name

      - name: Build solution
        run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Execute unit tests
        run: dotnet test $env:Test_Project_Path --no-build --verbosity normal
